# This is the makefile you need to use to compile the program.
# The only dependency is gcc, so you should be able to compile it on just about anything.
# This should go without saying, but you still need to compile it manually on Windows, since Windows doesn't come with a standard compiler I can call.

all:
	gcc InputString.c -o InputString
